X = int(input("Give me the first number : "))
Y = int(input("Give me the second number : "))
print("Thank you!")
print(f"{X} + {Y} = {X + Y}")
print(f"{X} - {Y} = {X - Y}")
print(f"{X} / {Y} = {X / Y}")
print(f"{X} * {Y} = {X * Y}")