Y = int(input("Please tell me your age : "))
print("You are currently" , Y , "years old")
print("In 10 years, you'll be " , Y+10 , "years old")
print("In 20 years, you'll be " , Y+20 , "years old")
print("In 30 years, you'll be " , Y+30 , "years old")